### ISSUE TITLE
javascript error in the customize page

### ISSUE THREAD

**Issue by x0rld** [LWJGL/lwjgl3-www#100]
hi,
there is an error about parsing json 

![image](https://user-images.githubusercontent.com/45242856/103456360-9bd41c80-4cf5-11eb-867a-d634af789786.png)

**Comment by apostolos** [comment]
Hi @x0rld,

Your client seems to be stuck in an old version. Can you please do a force refresh? That should fix the problem.

There should be an update button visible right next to the logo on the top left of the page. I can't see it on the screenshot but if it's there you can just click on it and the page will auto-upgrade to the latest version.

**Comment by x0rld** [comment]
![image](https://user-images.githubusercontent.com/45242856/103461980-68f44d80-4d22-11eb-8931-1ad537273b46.png)
oh yeah it should be a cache error :smile:
