### ISSUE TITLE
Add 'Unsupported Platforms' note to some bindings

### ISSUE THREAD

**Issue by SWinxy** [LWJGL/lwjgl3-www#104]
As LWJGL begins to support macOS ARM64 and Windows ARM64 (and potentially more in the future), listing supported platforms for a binding can be unhelpful. It becomes too long if it supports most platforms. Making a note of _unsupported_ platforms would make it easier to read.

Eg. bgfx:
![image](https://user-images.githubusercontent.com/8303399/110253060-55e63f80-7f56-11eb-9e1d-406b0d64feb8.png)
becomes
![image](https://user-images.githubusercontent.com/8303399/110253307-9e522d00-7f57-11eb-9bcc-40c285b44194.png)

Eg. Meow hash:
![image](https://user-images.githubusercontent.com/8303399/110253347-d6f20680-7f57-11eb-81dd-fec9914009fa.png)
becomes
![image](https://user-images.githubusercontent.com/8303399/110253473-80d19300-7f58-11eb-88eb-f5213726173e.png)

Shorter lists of supported platforms would remain:
![image](https://user-images.githubusercontent.com/8303399/110253518-caba7900-7f58-11eb-97b4-ac48de0418c5.png)

**Comment by apostolos** [comment]
You have a point.

Thanks! on it.

**Comment by apostolos** [comment]
Ended up displaying a different list depending on which is sorter:

![image](https://user-images.githubusercontent.com/41679/110257968-e9e0f700-7fa8-11eb-85db-7709a27dca90.png)

**Comment by SWinxy** [comment]
Eyyy thanks @apostolos. A problem is that the items in the Release category say they don't support macos & windows on arm, even though those platforms aren't an option.

**Comment by apostolos** [comment]
@SWinxy I agree it's not ideal but this problem will go away with the next stable release since all these platforms will be supported.

My thinking is that, in the future, users looking at older LWJGL versions will want to know that a specific binding is not available on their platform. Although we hide the applicable platforms for a specific version (left-side radio list), we still show platform availability for all _present_ available platforms. Try selecting a really old version in the _Release_ tab to see what I mean.

But maybe I'm wrong, @Spasi what do you think?

**Comment by SWinxy** [comment]
I'm a little confused by the inconsistency. I think you mean to say that each binding in older versions will list the supported platforms out of the current (larger) list of platforms, but for some of the bindings (eg 3.1.0), there is no note. Is it saying that those are platform-independent?
![image](https://user-images.githubusercontent.com/8303399/110340508-597dd300-7ff7-11eb-95ed-cf6f18a92336.jpeg)

**Comment by apostolos** [comment]
Yes, the ones with no note are available on all platforms (@Spasi please confirm).

I agree that it can be confusing and I'm open to suggestions.

**Comment by Spasi** [comment]
> But maybe I'm wrong, @Spasi what do you think?

The natives list is updated when you select an older LWJGL version. The supported platform warnings should be updated according to that list.

> Yes, the ones with no note are available on all platforms (@Spasi please confirm).

Correct. For example, LWJGL doesn't ship any natives for OpenCL. It uses whatever OpenCL implementation is available on the user's system.

**Comment by SWinxy** [comment]
Awesome! Thanks.
