### ISSUE TITLE
lwjgl.org displays "Loading..." on Safari

### ISSUE THREAD

**Issue by Shujito** [LWJGL/lwjgl3-www#108]
The page currently looks like this:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/1296326/120872888-3a8ece80-c55d-11eb-97b5-3d89f6e25816.png">

The problem seems to be the compiled javascript code:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/1296326/120872794-ed126180-c55c-11eb-8bc3-254266053c2c.png">

I'm currently using Safari 13.0.5 on MacOS Mojave:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1296326/120872833-09ae9980-c55d-11eb-8575-4f5229f14e5a.png">

I have already deleted cache, and tried lading the page on incognito mode for better measure

**Comment by apostolos** [comment]
Fixed, thanks!
