### ISSUE TITLE
OpenXR is listed under releases

### ISSUE THREAD

**Issue by SWinxy** [LWJGL/lwjgl3-www#118]
OpenXR was only recently added to LWJGL, but it's only supported in the snapshots.

**Comment by apostolos** [comment]
It's only listed when you select early access:

This is what I see when I select the stable build:
![image](https://user-images.githubusercontent.com/41679/150654144-47917500-4e54-4695-a42d-9b6f265aebf2.png)

**Comment by SWinxy** [comment]
Odd. It was listed under the releases tab, but I didn't get a screenshot. Hmm. I'll reopen if I see it again.
