### ISSUE TITLE
Possibly incompatible Gradle script: No signature of method

### ISSUE THREAD

**Issue by DesertCookie** [LWJGL/lwjgl3-www#120]
Copying the Gradle code provided on the [customize](https://www.lwjgl.org/customize) page I get the following error:
```
No signature of method: static org.gradle.nativeplatform.platform.OperatingSystem.current() is applicable for argument types: () values: []
```
As the error states, this happens in the first line of the switch statement generating the name of the native files.

My environment:
- Java 17.0.2 (from Adoptium.net)
- Gradle 7.3.3
- IntelliJ IDEA Ultimate 2021.1.1

**Comment by Spasi** [comment]
@DesertCookie Thanks!
