### ISSUE TITLE
"Failed to fetch" when downloading as ZIP

### ISSUE THREAD

**Issue by SWinxy** [LWJGL/lwjgl3-www#121]
To replicate, select any combination of platform natives in 3.3.0, and select OpenAL to put in.

![image](https://user-images.githubusercontent.com/8303399/152700378-f46f941d-26c6-41e5-8d89-a8b343c2dee3.png)

**Comment by apostolos** [comment]
3.3.0 fixed!
3.2.3 and below are still broken.

We're in the process of finalizing the move of LWJGL to it's own independent [AWS](https://aws.amazon.com/) account.

Unfortunately we cannot re-use the same S3 buckets and had to create new ones. We are still finalizing the re-configuration (CI, download links, etc).

I will update this thread when everything is in order.

**Comment by apostolos** [comment]
Early access build also working properly.

**Comment by apostolos** [comment]
All fixed.

**Comment by SWinxy** [comment]
Awesome. Thanks!
