### ISSUE TITLE
Generated POM does not conform to the POM Code Convention

### ISSUE THREAD

**Issue by stelar7** [LWJGL/lwjgl3-www#23]
The POM generated from the /download page does not output a POM that follows the [POMCC](https://maven.apache.org/developers/conventions/code.html#POM_Code_Convention). 
A simple fix is to move the `<profiles>` to the end of the POM.

**Comment by apostolos** [comment]
@stelar7 If I'm reading it correctly, we should also move <repositories /> under <dependencies /> and separate each element by a new line.
