### ISSUE TITLE
Cannot render html in production mode?

### ISSUE THREAD

**Issue by afrianjunior** [LWJGL/lwjgl3-www#27]
in my case, react can't render html in production mode, im run ``` npm run start-production ```

**Comment by apostolos** [comment]
Before launching to test in production mode, you need to run:
```
npm run release
```

That's because it expects to find the final generated minified files on disk.

Hmm, I should probably rename it to "test-production" and throw if files are not there.

**Comment by afrianjunior** [comment]
yes i run ``` npm run release ``` before run start-production

so, how to make this app render html?

**Comment by apostolos** [comment]
Do you mean server-side HTML rendering? We've completely removed server-side rendering some months ago because we had serious issues with memory leaks bringing down the server and also unnecessarily increasing code complexity.

**Comment by afrianjunior** [comment]
okay, thanks for your response :)
