### ISSUE TITLE
Download customize form unexpected behaviour

### ISSUE THREAD

**Issue by otoomey** [LWJGL/lwjgl3-www#45]
Browser: Firefox Quantum (64-bit) 58.0.1

To reproduce:
On website, go 'download' page > 'customize LWJGL 3' > Enable 'Gradle' > Enable 'Custom'. Add any of the libraries/frameworks.

Expected Behavior:
The library/framework checkbox should be highlighted

Actual Behavior:
The checkbox does not highlight. The preset jumps from 'custom' to 'getting started' (Or whatever it was set at before 'custom'). 

[Here](https://drive.google.com/file/d/1pMRZjsyoChWilrJWIWZMDFbBE55FmDMb/view?usp=sharing) is a GIF showing the problem.

**Comment by apostolos** [comment]
Thanks @otoomey,

The checkboxes were broken because of a bad deploy.

However we've made a change to the "presets" behavior. To avoid confusion, the custom option is disabled by default. When the contents do not match any of the pre-defined presets, "custom" is automatically enabled and checked.
