### ISSUE TITLE
Mention "-XstartOnFirstThread" requirement for macOS in "Get Started"

### ISSUE THREAD

**Issue by TheMrMilchmann** [LWJGL/lwjgl3-www#81]
> On macOS the JVM must be started with the -XstartOnFirstThread argument for GLFW to work. This is necessary because most GLFW functions must be called on the main thread and the Cocoa API on macOS requires that thread to be the first thread in the process. For this reason, on-screen GLFW windows and the GLFW event loop are incompatible with other window toolkits (such as AWT/Swing or JavaFX) on macOS. Off-screen GLFW windows can be used with other window toolkits, but only if the window toolkit is initialized before GLFW.

https://javadoc.lwjgl.org/org/lwjgl/glfw/package-summary.html

Issues in which the `-XstartOnFirstThread` flag is missing and consequently the JVM crashing are commonly raised in the forum, StackOverflow and on GitHub. While the requirement is documented in many places, the "Get Started" section on the website does not mention the flag at all. In my opinion, it is reasonable to expect users to read a bit of documentation but I doubt that added visibility could inflict any harm.

It is also worth noting that there are some existing checks for this in LWJGL. (See [EventLoop](https://github.com/LWJGL/lwjgl3/blob/c65c15bcbe7dbb9c1ebdda141f2d8bff8fceaebd/modules/lwjgl/glfw/src/main/java/org/lwjgl/glfw/EventLoop.java#L28).) However, as recent reports have shown they are somewhat unreliable and may break on some macOS versions, leaving the user clueless. [[lwjgl3#538](https://github.com/LWJGL/lwjgl3/issues/538)]

**Comment by apostolos** [comment]
Closed via 6dbe1f9e6eadfa779e6baa9542986f5d1ce03e3b
