### ISSUE TITLE
OpenVR bindings for Windows x86

### ISSUE THREAD

**Issue by knokko** [LWJGL/lwjgl3-www#84]
When I tried to generate a build.gradle for file using OpenVR bindings on Windows x86 with the build configurator (https://www.lwjgl.org/customize), the OpenVR checkbox got disabled when I selected the Windows x86 natives (see the screenshot I made).
![openvrx86](https://user-images.githubusercontent.com/29510261/79483046-fb788380-8011-11ea-888c-2c80cf7968f4.png)

But why is that? It seems that such natives for Windows x86 are just available when I manually add it to the build.gradle and build it (the natives are just in the produced jar when I open it with an archive manager).

**Comment by Spasi** [comment]
Thanks!
