### ISSUE TITLE
Customize Page Includes Broken Link to Intel SSE

### ISSUE THREAD

**Issue by SWinxy** [LWJGL/lwjgl3-www#94]
The customize page (when showing descriptions) links to https://software.intel.com/en-us/node/523328, which redirects to the developer homepage. [This page](https://software.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-reference/intrinsics.html) might be the new one to link to.

**Comment by apostolos** [comment]
Fixed via 9024cbf8e1a41f3d963198570d58d6925a96f0f8
