### ISSUE TITLE
[Design Decision Question] why change to recoil from valtio?

### ISSUE THREAD

**Issue by jeremy-coleman** [LWJGL/lwjgl3-www#96]
I've been considering moving over a huge project from mobx to valtio , so I'm really curious what prompted the change. Any insight would be appreciated! I have been skeptical of valtio's performance for large store <-> component graphs since it doesn't highjack render directly

**Comment by apostolos** [comment]
Nothing in particular, just testing out the latest state management libs. I was curious how one could model external state sync (e.g. a matchMedia query) with Recoil.

I do have some concerns about Valtio's compatibility with Concurrent Mode (which this project uses). I will let some time pass before I re-evaluate it. See if it gets adoptions from other projects, etc.

Valtio was dead-simple to use and with almost no ceremony. You will appreciate its simplicity coming from MobX and other libs. It's very small too. However I never modeled anything complicated with it, so I don't know how it holds up in larger projects.
